import "../styles/globals.css";
import { Inter } from "next/font/google";
import Header from "./components/atoms/atoms/atoms/Header";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>Proyecto React</title>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
